### ISSUE TITLE
Syntax error in generated content.js on main

### ISSUE THREAD

**Issue by mythmon** [mozilla-extensions/normandy-devtools#453]
I noticed that the generated `content.js` has a syntax error, as reported by Firefox and Node. This shows up when I run `yarn watch` and also `yarn build`. I don't really understand it though. I don't think it's coming from any of our code, since ESLint isn't catching it, which implies it is part of our build process. Looking at the generated source code, I don't understand how the error *is* an error, and I don't understand how it got here.

I did a git bisect, and it points at either #451, or #442, depending on how I test. Neither of those make sense to me, since the `dotenv-webpack` bump looks unrelated to anything we do, and an update to `@testing-framework/react` shouldn't affect the build.

**Comment by mythmon** [comment]
Here's the syntax error:

```bash
$ node --check dist/content.js
/home/mythmon/src/normandy-devtools/dist/content.js:53050
      .then(function(ret) { {"env": {}}.nextTick(cb, null, ret) },
                                  ^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:1101:16)
    at checkSyntax (internal/main/check_syntax.js:66:3)
    at internal/main/check_syntax.js:39:3
```

**Comment by mythmon** [comment]
Oh, I think I understand what happened now. Found this issue on their tracker: https://github.com/mrsteele/dotenv-webpack/issues/240
